metadata_dir = "/Users/fabienlefrapper/Developer/playground/garage-k2v/meta"
data_dir = "/Users/fabienlefrapper/Developer/playground/garage-k2v/data"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 1

compression_level = 2

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "f99f9c56d37c1f4b67e8991e28f8df38c8fbe017e50f90a46259e95c992bb909"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3903"
